var SEED = 1;
var SCREEN_WIDTH;
var SCREEN_HEIGHT;
var PI_2 = (Math.PI / 2);
var canvas, context;
var container, stats;
var controls;
var rayTracingShader, copyShader, postProcessingShader;
var rayTracingUniforms, copyUniforms, postProcessingUniforms;
var commonVert, rayTracingFragmentShader;
var copyFragmentShader;
var postProcessingFragmentShader;
var rayTracingGeometry, rayTracingMaterial, rayTracingQuad;
var copyGeometry, copyMaterial, copyQuad;
var postProcessingGeometry, postProcessingMaterial, postProcessingQuad;
var rayTracingRenderTarget, copyRenderTarget;
var quadCamera, worldCamera;
var renderer, clock;
var elapsedTime;
var oldYaw, oldPitch;
var pointerlockChange;
var cameraDirectionVector;
var cameraRightVector;
var cameraUpVector;
var cameraControls;
var yaw;
var pitch;
var canvas;
var cameraInfoElement;
var camHeight = 1.0;
var aperture = 0.0;
var focus = 1.0;
var pixelRatio = 1.0;
var keyLPressedOnce = false;
var windowIsBeingResized = false;
var sampleCounter = 0.0;
var frameCounter = 1.0;
var cameraIsMoving = false;
var cameraRecentlyMoving = false;
var isPaused = true;
var needsColorSwitch = false;
var disableSwitching = false;
var ableToEngagePointerLock = true;
